### ISSUE TITLE
Error with 'make install'

### ISSUE THREAD

**Issue by georgerichardson** [nestauk/ds-cookiecutter#103]
I cloned `https://github.com/nestauk/innovation_sweet_spots/` and tried to make a fresh install using `make install`. I recieved the following error:

```
conda env create -q -n innovation_sweet_spots -f environment.yaml
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... failed

ResolvePackageNotFound:
  - python=3.7
  - graph-tool

make: *** [conda-create] Error 1
```

From a bit of reading it looks like `ResolvePackageNotFound` is normally associated with very specific package versions specified in `environment.yaml` when this file is automatically generated using conda. However, this isn't the case here. From speaking with others, it seems like this could be an error with M1 Macs.

This is the `environment.yaml` used in this case:

```
channels:
  - defaults
  - conda-forge
dependencies:
  - pip
  - python=3.7
  - graph-tool
```

**Comment by bishax** [comment]
This isn't really an issue with `make install` or `ds-cookiecutter`, it looks like a Conda x M1 x graph-tool issue.
Closing issue here and moving to Slack to solve.
