### ISSUE TITLE
Guidelines do not fit my use-case

### ISSUE THREAD

**Issue by bishax** [nestauk/ds-cookiecutter#29]
Please use this issue to report any examples where any guidelines in the workflow do not fit your usecase.

**Comment by kstathou** [comment]
Two ideas:
* Loading an external model ([example](https://www.tensorflow.org/hub/overview)). Where should I store the data and code? 
* model.py and features.py could be merged in our case because we work more with unsupervised methods

**Comment by bishax** [comment]
> Two ideas:
> 
> * Loading an external model ([example](https://www.tensorflow.org/hub/overview)). Where should I store the data and code?
> * model.py and features.py could be merged in our case because we work more with unsupervised methods

* Store the data in `models/`
* Perhaps a clearer delineation between `models` and `features` folders (or files) could be made by changing to `transformers` and `estimators` (e.g. sklearn or spark - https://spark.apache.org/docs/1.6.0/ml-guide.html#transformers).
   * **Transformer** - for feature transformations and learned models.
      Implements `transform()` which takes in data and produces data.
   * **Estimator** - abstracts the concept of a learning algorithm or any algorithm that fits or trains on data.
      Implements `fit()` which takes in data and produces a model that is a transformer.

The `estimators/` and `transformers/` separation is practical as we know that anything in `transformers/` will not be doing any kind of fitting on data.

Additional point/proposal: Modules/Functions should only be placed in `estimators/` and `transformers/` if they are generally applicable code. Code relating purely to one dataset (e.g. GTR) should be in a dataset dependent folder (e.g. `gtr/`) **but** it is preferred to write code that can go in `estimators/`/`transformers/`.
