### ISSUE TITLE
Importing virtual environment packages in Jupyter

### ISSUE THREAD

**Issue by Juan-Mateos** [nestauk/ds-cookiecutter#70]
There are a couple of extra steps required to import packages installed in the virtual environment when using a global jupyter installation. They are:

1. `python -m ipykernel install --user --name=VENV_NAME`
2. In the notebook, change the kernel to VENV_NAME

Worth adding to the documentation [here](https://nestauk.github.io/ds-cookiecutter/structure/#dont-install-jupyterjupyterlab-in-your-environment-use-ipykernel)?

**Comment by bishax** [comment]
Thanks for flagging.
(I've been using notebooks through vscode recently which doesn't require this setup).

**Comment by bishax** [comment]
Closed by #83
